on: [push, pull_request]
name: Test
jobs:
  testOpenJDK8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    #One task
    - uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-8
      with:
        args: test
    #Default task
    - uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-8
    #Multiple tasks
    - uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-8
      with:
        args: build test
    #version
    - uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-8
      with:
        args: --version
  testOpenJDK11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      #One task
      - uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-11
        with:
          args: test
      #Default task
      - uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-11
      #Multiple tasks
      - uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-11
        with:
          args: build test
      #version
      - uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-11
        with:
          args: --version
  testOpenJDK13:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      #One task
      - uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-13
        with:
          args: test
      #Default task
      - uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-13
      #Multiple tasks
      - uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-13
        with:
          args: build test
      #version
      - uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-13
        with:
          args: --version