on: [push, pull_request]
name: Test
jobs:
  testLibrary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        action:
          - MrRamych/gradle-actions/openjdk-8@migrate-to-new-syntax
          - MrRamych/gradle-actions/openjdk-11@migrate-to-new-syntax
          - MrRamych/gradle-actions/openjdk-12@migrate-to-new-syntax
    steps:
    - uses: actions/checkout@master
    #Simple
    - uses: ${{ matrix.action }}
      with:
        args: test
    #Default task
    - uses: ${{ matrix.action }}
    #Multiple task
    - uses: ${{ matrix.action }}
      with:
        args: build test
    #Mutiple task YAML way
    - uses: ${{ matrix.action }}
      with:
        args: build test
