on: [push, pull_request]
name: Test
jobs:
  testOpenJDK8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    #Simple
    - uses: MrRamych/gradle-actions/openjdk-8@3.1
      with:
        args: test
    #Default task
    - uses: MrRamych/gradle-actions/openjdk-8@3.1
    #Multiple task
    - uses: MrRamych/gradle-actions/openjdk-8@3.1
      with:
        args: build test
  testOpenJDK11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      #Simple
      - uses: MrRamych/gradle-actions/openjdk-11@3.1
        with:
          args: test
      #Default task
      - uses: MrRamych/gradle-actions/openjdk-11@3.1
      #Multiple task
      - uses: MrRamych/gradle-actions/openjdk-11@3.1
        with:
          args: build test
  testOpenJDK12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      #Simple
      - uses: MrRamych/gradle-actions/openjdk-12@3.1
        with:
          args: test
      #Default task
      - uses: MrRamych/gradle-actions/openjdk-12@3.1
      #Multiple task
      - uses: MrRamych/gradle-actions/openjdk-12@3.1
        with:
          args: build test
  testOpenJDK13:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      #Simple
      - uses: MrRamych/gradle-actions/openjdk-13@3.1
        with:
          args: test
      #Default task
      - uses: MrRamych/gradle-actions/openjdk-13@3.1
      #Multiple task
      - uses: MrRamych/gradle-actions/openjdk-13@3.1
        with:
          args: build test
