on: [push, pull_request]
name: Test
jobs:
  testLibrary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - 8
          - 11
          - 12
    steps:
    - uses: actions/checkout@master
    #Simple
    - uses: "MrRamych/gradle-actions/openjdk-${{ matrix.java }}@migrate-to-new-syntax"
      with:
        args: test
    #Default task
    - uses: MrRamych/gradle-actions/openjdk-${{ matrix.java }}@migrate-to-new-syntax
    #Multiple task
    - uses: MrRamych/gradle-actions/openjdk-${{ matrix.java }}@migrate-to-new-syntax
      with:
        args: build test
    #Mutiple task YAML way
    - uses: MrRamych/gradle-actions/openjdk-${{ matrix.java }}@migrate-to-new-syntax
      with:
        args: build test
