on: [push, pull_request]
name: Test
jobs:
  testOpenJDK8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    #Simple
    - uses: MrRamych/gradle-actions@v4.0-openjdk-8
      with:
        args: test
    #Default task
    - uses: MrRamych/gradle-actions@v4.0-openjdk-8
    #Multiple task
    - uses: MrRamych/gradle-actions@v4.0-openjdk-8
      with:
        args: build test
  testOpenJDK11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      #Simple
      - uses: MrRamych/gradle-actions@v4.0-openjdk-11
        with:
          args: test
      #Default task
      - uses: MrRamych/gradle-actions@v4.0-openjdk-11
      #Multiple task
      - uses: MrRamych/gradle-actions@v4.0-openjdk-11
        with:
          args: build test
  testOpenJDK13:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      #Simple
      - uses: MrRamych/gradle-actions@v4.0-openjdk-13
        with:
          args: test
      #Default task
      - uses: MrRamych/gradle-actions@v4.0-openjdk-13
      #Multiple task
      - uses: MrRamych/gradle-actions@v4.0-openjdk-13
        with:
          args: build test